### ISSUE TITLE
🛑 Void Bin is down

### ISSUE THREAD

**Issue by DanPlayz0** [TheVoidDevs/vdstatus#1]
In [`3e621c2`](https://github.com/TheVoidDevs/vdstatus/commit/3e621c29eb843470f434c8752ff4365413ea830e
), Void Bin (https://voidbin.cc) was **down**:
- HTTP code: 502
- Response time: 164 ms

**Comment by DanPlayz0** [comment]
Testing downtime

**Comment by AshMW2724** [comment]
Another response
